openapi: 3.0.0
info:
  title: Shop app backend - 2024
  description: API collection of shop application
  version: 1.0.0
  termsOfService: http://swagger.io/terms
  contact:
    email: nvh1892kw@gmail.com

servers:
  - url: http://localhost:1892/api/v1

tags:
  - name: auth
    description: Authentication api
  - name: user
    description: User api collection
  - name: role
    description: role api collection
paths:
  /auth/login:
    post:
      tags:
        - auth
      summary: Login to the system
      description: Login to service with phone number and password
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login successful
          headers:
            Set-Cookie:
              description: Session cookie
              schema:
                type: string
        '401':
          description: Unauthorized
        '400':
          description: Bad request
  /auth/logout:
    post:
      tags:
        - auth
      summary: Login to the system
      description: Login to service with phone number and password
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Successful login
          headers:
            Set-Cookie:
              description: Session cookie
              schema:
                type: string
        '401':
          description: Unauthorized
        '400':
          description: Bad request
components:
  schemas:
    LoginRequest:
      type: object
      properties:
        phone_number:
          type: string
          example: ""
        password:
          type: string
          example: "pass"
      required:
        - phone_number
        - password