server:
  port: 1892
  servlet:
    context-path: /api/v1/
spring:
  servlet:
    multipart:
      max-file-size: 10MB
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
jwt:
  signerKey: SpringBootTrainingsdfhsdfgsr4gsfgsregsfgsfdg#$%S%G
  valid-duration: 3600
  refreshable-duration: 120

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    doc-expansion: none
  api-docs:
    path: /api-docs
  show-actuator: true

logging:
  level:
    org.springframework.aop: debug